variable "storage_account_name" {}
variable "storage_container_name" {}
variable "storage_blob_name" {}
variable "storage_share_name" {}
variable "bootdiag_storage_account_name" {}
variable "account_tier" {}
variable "account_repl_type" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "vnet_address_space" {}
variable "subnet_address_prefix" {}
variable "lb_name" {}
variable "nsg_name" {}
variable "resource_group_name" {}
variable "resource_group_location" {}